version: '3.8'

services:
  # Banco de Dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: postgres-users
    environment:
      POSTGRES_DB: libri-users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    ports:
      - "5437:5432"  # Porta do seu notebook: Porta do container
    volumes:
      # Persistir dados do banco
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres-data: